name: Development Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
      - name: Install dependencies
        run: npm i
      - name: Linting
        run: npm run lint
      - name: Testing
        run: npm test
