name: Development Workflow

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.1.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.1.0
      - name: Install dependencies
        run: npm i
      - name: Checking lint
        run: npm run lint --fix
      - name: Testing
        run: npm run test