name: Development Workflow

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    name: CI Pipeline
    runs-on: node:12.19.0-alpine3.12
    steps:
      - name: Install dependencies
        run: npm i
      - name: Checking lint
        run: npm run lint --fix
      - name: Testing
        run: npm run test